language: node_js
node_js:
  - lts/*
# whitelist, https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches
branches:
  only:
  - production

install:
  - npm install
  - npm run docs:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  keep_history: true
  target-branch: master
  local-dir: docs/.vuepress/dist
  on:
    branch: production